### ISSUE TITLE
Strange coloring of 4D maps with positive and negative values

### ISSUE THREAD

**Issue by ezaezaeza** [equinor/webviz-subsurface#311]
I suspect that there is something wrong with the coloring of maps in the Surface viewer, when there are both positive and negative values in the map.  The maps in the attachment should look similar, but in webvis, the coloring does not seem to be symmetric around 0.
![webvis_4D_map](https://user-images.githubusercontent.com/64018861/79758251-73e68980-831d-11ea-9ebd-307431a1105c.jpg)
![coviz_4D_map](https://user-images.githubusercontent.com/64018861/79758254-7517b680-831d-11ea-9777-2addab707c55.jpg)

**Comment by asnyv** [comment]
@ezaezaeza have you tried defining the max/min range in the yaml-config, similar to how it is done for stoiip in the example? See the `attribute_settings` below. Should be similar to the user defined range in the other figure you attached.
Adding a `symmetric: True` option could of course be an idea, as the range isn't always well known in advance. And as you say, it could also be considered to be default behavior if both positive and negative values are present. 
```
  - title: Surface viewer (FMU)
    content:
      - SurfaceViewerFMU:
          ensembles:
            - iter-0
            - iter-3
          wellfolder:
            ../observed_data/wells
          attribute_settings:
            stoiip:
              min: 0
              max: 2
              color: inferno
```
