### ISSUE TITLE
ParameterAnalysis plugin requires a FIELD vector

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface#591]
**Describe the bug**
`ParameterAnalysis` crashes on initalization if not a `FIELD` vector is provided.
This is due to the [vector selector](https://github.com/equinor/webviz-subsurface/blob/9c982ba3793cfe1c3c40c18a36a318a6114527fe/webviz_subsurface/plugins/_parameter_analysis/views/selector_view.py#L35) is initialized with field vectors

**How to reproduce**
Using the reek example dataset with the following configuration:
```yaml
title: Reek Webviz Example
shared_settings:
  scratch_ensembles:
    sens_run: ../reek_fullmatrix/realization-*/iter-0
    iter-0: ../reek_history_match/realization-*/iter-0
    iter-1: ../reek_history_match/realization-*/iter-1
    iter-2: ../reek_history_match/realization-*/iter-2
    iter-3: ../reek_history_match/realization-*/iter-3
pages:

  - title: Parameter analysis
    content:
      - ParameterAnalysis:
          ensembles:
            - iter-0
            - iter-1
            - iter-2
            - iter-3
          column_keys:
            - WOPR:*
  ````

**Expected behavior**
Should initialize with the available vectors.
